version: '2'

services:
    aplicacion1:
        container_name: aplicacion1
        stdin_open: true
        build:
            context: ../../builds/react
        command: npm start --host 0.0.0.0
        restart: always
        ports:
            - 3000:3000
        # volumes:
        #     - ../../source/light-blue-react-template-master:/app
        environment:
            - CHOKIDAR_USEPOLLING=true        